# Soil Fertility Chemical Content Required Prediction

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("crop.csv")

N = Nitrogen

P = phosphorous

K = Potassium

Ph = A scale used to identify acidity or basicity nature; (Acid Nature- Ph<7; 
Neutral- Ph=7; Base Nature-P>7)

EC = Electrical Conductivity

OC = Organic Carbon

S = Sulphur

zn = zinc

Fe = iron

Cu = Copper

Mn = Magnesium

B = Boron



In [5]:
df

N     P    K    pH    EC    OC      S    Zn    Fe    Cu     Mn     B  \
0    138   8.6  560  7.46  0.62  0.70   5.90  0.24  0.31  0.77   8.71  0.11   
1    213   7.5  338  7.62  0.75  1.06  25.40  0.30  0.86  1.54   2.89  2.29   
2    163   9.6  718  7.59  0.51  1.11  14.30  0.30  0.86  1.57   2.70  2.03   
3    157   6.8  475  7.64  0.58  0.94  26.00  0.34  0.54  1.53   2.65  1.82   
4    270   9.9  444  7.63  0.40  0.86  11.80  0.25  0.76  1.69   2.43  2.26   
..   ...   ...  ...   ...   ...   ...    ...   ...   ...   ...    ...   ...   
875  351  10.7  623  7.96  0.51  0.29   7.24  0.36  4.69  0.69  11.03  0.69   
876  264   9.0  486  7.24  0.47  0.10   3.92  0.35  8.26  0.45   7.98  0.40   
877  276   9.2  370  7.62  0.62  0.49   6.64  0.42  3.57  0.63   6.48  0.32   
878  320  13.8  391  7.38  0.65  1.07   5.43  0.58  4.58  1.02  13.25  0.53   
879  264  10.3  475  7.49  0.74  0.88  10.56  0.45  7.36  1.87  10.63  0.63   

     Output  
0         0  
1         0  
2         0  
3         0  
4         1  
..      ...  
875       1  
876       1  
877       1  
878       2  
879       0  

[880 rows x 13 columns]

In [6]:
X = df.iloc[:, :-1].values
X

array([[1.380e+02, 8.600e+00, 5.600e+02, ..., 7.700e-01, 8.710e+00,
        1.100e-01],
       [2.130e+02, 7.500e+00, 3.380e+02, ..., 1.540e+00, 2.890e+00,
        2.290e+00],
       [1.630e+02, 9.600e+00, 7.180e+02, ..., 1.570e+00, 2.700e+00,
        2.030e+00],
       ...,
       [2.760e+02, 9.200e+00, 3.700e+02, ..., 6.300e-01, 6.480e+00,
        3.200e-01],
       [3.200e+02, 1.380e+01, 3.910e+02, ..., 1.020e+00, 1.325e+01,
        5.300e-01],
       [2.640e+02, 1.030e+01, 4.750e+02, ..., 1.870e+00, 1.063e+01,
        6.300e-01]])

In [7]:
Y = df.iloc[:, -1].values
Y

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 2, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 2, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) 
X_test = sc.transform(X_test) 

## Using Logistic Regression

In [10]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 0)
model.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [11]:
y_pred = model.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 2]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 2]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 2]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [2 2]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 2]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 2]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 2]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [2 1]
 [1 1]
 [1 1]

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix: ")
print(cm)

print("Accuracy of the Model: {0}%".format(accuracy_score(y_test, y_pred)*100))

Confusion Matrix: 
[[96  9  0]
 [ 6 96  1]
 [ 0 11  1]]
Accuracy of the Model: 87.72727272727273%


## Random Forest Regression /classification change/ dataset change using smoke technique

In [13]:
# Fitting Random Forest Regression to the dataset
# import the regressor
from sklearn.ensemble import RandomForestRegressor

# create regressor object
regressor = RandomForestRegressor(n_estimators=100, random_state=0)

# fit the regressor with x and y data
regressor.fit(X, Y)

RandomForestRegressor(random_state=0)

In [14]:
y_pred = regressor.predict(X_test)
y_pred = np.round(y_pred)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1. 0.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [1. 2.]
 [1. 1.]
 [1. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 1.]
 [1. 0.]
 [0. 0.]
 [1. 2.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 1.]
 [1. 2.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [1. 2.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 1.]
 [1. 0.]
 [0. 1.]
 [1. 1.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 0.]
 [1. 2.]
 [1. 1.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 1.]
 [1. 1.]
 [1. 0.]
 [1. 0.]
 [1. 1.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 2.]
 [1. 0.]
 [1. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [1. 1.]
 [1. 0.]
 [1. 1.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 2.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 0.]
 [1. 0.]
 [1. 0.]
 

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix: ")
print(cm)

print("Accuracy of the Model: {0}%".format(accuracy_score(y_test, y_pred)*100))

Confusion Matrix: 
[[15 90  0]
 [17 86  0]
 [ 1 11  0]]
Accuracy of the Model: 45.909090909090914%


## K-Nearest Neighbour

In [16]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=7)
  
knn.fit(X_train, y_train)
  
# Predict on dataset which model has not seen before
print(knn.predict(X_test))



[0 0 1 1 1 0 1 1 0 1 1 0 0 1 1 1 1 0 0 1 1 0 1 0 1 0 1 1 1 0 1 1 0 0 0 0 1
 1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 1 0 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0
 0 1 0 1 0 0 1 1 1 1 1 1 1 1 1 0 0 1 0 0 1 0 0 0 0 1 0 1 1 0 1 0 1 0 0 1 0
 1 1 0 0 0 1 0 1 0 0 0 1 1 1 1 0 1 0 0 1 0 0 0 1 1 0 1 1 0 1 1 1 0 1 0 0 0
 1 1 0 1 1 0 1 0 0 0 1 0 1 0 1 0 1 1 1 1 1 1 0 1 0 1 0 1 1 1 1 0 0 1 1 1 1
 0 1 0 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 1 0]


In [17]:
y_pred = knn.predict(X_test)
y_pred = np.round(y_pred)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 2]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 2]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 2]
 [0 1]
 [1 1]
 [0 0]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 2]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 2]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 2]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 2]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 2]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix: ")
print(cm)

print("Accuracy of the Model: {0}%".format(accuracy_score(y_test, y_pred)*100))

Confusion Matrix: 
[[88 17  0]
 [14 89  0]
 [ 0 12  0]]
Accuracy of the Model: 80.45454545454545%


## Decision Tree

In [19]:
from sklearn.tree import DecisionTreeClassifier

# Creating the classifier object
clf_gini = DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=3, min_samples_leaf=5)
  
# Performing training
clf_gini.fit(X_train, y_train)

# Decision tree with entropy
clf_entropy = DecisionTreeClassifier(
            criterion = "entropy", random_state = 100,
            max_depth = 3, min_samples_leaf = 5)
  
# Performing training
clf_entropy.fit(X_train, y_train)

y_pred = clf_gini.predict(X_test)
print("Predicted values:")
print(y_pred)

print("Confusion Matrix: ",confusion_matrix(y_test, y_pred))
      
print("Accuracy : ",accuracy_score(y_test,y_pred)*100)

from sklearn.metrics import classification_report
print("Report : ",classification_report(y_test, y_pred))

Predicted values:
[0 0 1 1 2 1 1 1 0 0 1 0 0 1 1 1 1 0 0 1 2 0 1 0 0 0 1 1 1 0 2 2 1 0 0 0 1
 1 0 2 1 1 0 0 0 1 1 1 0 2 1 0 1 1 1 1 1 0 0 1 0 1 1 0 0 1 1 1 0 1 1 1 1 0
 0 2 0 1 0 0 1 1 0 2 1 0 1 1 0 0 1 1 0 0 1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0
 1 0 0 0 0 0 0 1 0 0 0 1 1 1 1 0 1 0 0 1 0 0 0 1 1 0 1 1 0 1 1 1 0 2 0 1 0
 1 1 0 1 1 0 1 0 0 0 2 1 1 0 0 0 1 1 1 0 1 1 0 1 0 1 0 1 0 1 1 0 0 1 1 1 1
 0 1 0 0 0 1 0 0 1 1 0 1 0 1 0 0 2 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 1 0]
Confusion Matrix:  [[98  7  0]
 [ 7 93  3]
 [ 0  4  8]]
Accuracy :  90.45454545454545
Report :                precision    recall  f1-score   support

           0       0.93      0.93      0.93       105
           1       0.89      0.90      0.90       103
           2       0.73      0.67      0.70        12

    accuracy                           0.90       220
   macro avg       0.85      0.83      0.84       220
weighted avg       0.90      0.90      0.90       220



## Artificial Neural Network

In [20]:
import keras
from keras.models import Sequential
from keras.layers import Dense

classifier = Sequential()



ModuleNotFoundError: No module named 'keras'

**Added the input layer and the first hidden layer**






*  Sequential Class. output_dim represents the number of hidden neurons in the hidden layer.

*  The activation function in the hidden layer for a fully connected neural network should be the Rectifier Activation function. That’s why I use ‘relu’.

*  we have 12 independent variables,That’s why input_dim = 12.

In [21]:
classifier.add(Dense(units = 6,  kernel_initializer = 'uniform', activation = 'relu', input_dim = 12))

NameError: name 'classifier' is not defined

Added the second hidden layer

In [22]:
classifier.add(Dense(units = 6,  kernel_initializer = 'uniform', activation = 'relu'))

NameError: name 'classifier' is not defined

Add the output layer

In [29]:
classifier.add(Dense(units = 1,  kernel_initializer = 'uniform', activation = 'sigmoid'))

**Train ANN**

The training part requires two steps- Compile the ANN, and Fit the ANN to the Training set.   

Compile ANN

In [30]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Fit ANN to Training set

In [31]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
66/66 [==============================] - 1s 1ms/step - loss: 0.6909 - accuracy: 0.5045
Epoch 2/100
66/66 [==============================] - 0s 1ms/step - loss: 0.6676 - accuracy: 0.5106
Epoch 3/100
66/66 [==============================] - 0s 1ms/step - loss: 0.5839 - accuracy: 0.5106
Epoch 4/100
66/66 [==============================] - 0s 1ms/step - loss: 0.4655 - accuracy: 0.5485
Epoch 5/100
66/66 [==============================] - 0s 1ms/step - loss: 0.3568 - accuracy: 0.7773
Epoch 6/100
66/66 [==============================] - 0s 1ms/step - loss: 0.2643 - accuracy: 0.8242
Epoch 7/100
66/66 [==============================] - 0s 2ms/step - loss: 0.1864 - accuracy: 0.8485
Epoch 8/100
66/66 [==============================] - 0s 1ms/step - loss: 0.1130 - accuracy: 0.8576
Epoch 9/100
66/66 [==============================] - 0s 2ms/step - loss: 0.0402 - accuracy: 0.8667
Epoch 10/100
66/66 [==============================] - 0s 1ms/step - loss: -0.0322 - accuracy: 0.8682
Epoch 11

Predicting Test Result

In [32]:
y_pred = classifier.predict(X_test)
y_pred = np.round(y_pred)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

7/7 [==============================] - 0s 2ms/step
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 2.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 2.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 2.]
 [0. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 2.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 2.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 2.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 1.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 2.]
 [0.

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[95 10  0]
 [ 8 95  0]
 [ 0 12  0]]


0.8636363636363636